
networks:
  ctfd_network:
    driver: bridge
  web_challenges:
    driver: bridge
  misc_challenges:
    driver: bridge
  binary_challenges:
    driver: bridge


services:
  ctfd:
    image: ctfd/ctfd:latest
    ports:
      - "8000:8000"
      
    networks:
      - ctfd_network


  web1:
    build: ./challs/web/ssl/site
    ports:
      - "8001:80"
    volumes:
      - ./challs/web/ssl/site/index.php:/var/www/html/index.php
      - ./challs/web/ssl/site/logout.php:/var/www/html/logout.php
      - ./challs/web/ssl/site/V5jPCZdP.php:/var/www/html/V5jPCZdP.php
      - ./challs/web/ssl/site/welcome.php:/var/www/html/welcome.php
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

    networks:
      - web_challenges


  web2:
    build: ./challs/web/yourAPI/site
    ports:
      - "8002:80"
    volumes:
      - ./challs/web/yourAPI/site/files:/var/www/files
      - ./challs/web/yourAPI/site/index.php:/var/www/html/index.php
      - ./challs/web/yourAPI/site/.env:/var/www/.env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

    networks:
      - web_challenges

  web4:
    build: ./challs/web/ytrecommender/site
    ports:
      - "8004:4567"
    environment:
      FLAG: "flagflagflag"
    restart: unless-stopped

    networks:
      - web_challenges

  misc1:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10010:1337'
    volumes:
      - './challs/misc/stampante/src.py:/home/user/chall.py:ro'
      - './challs/misc/stampante/art.txt:/home/user/art.txt:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{asdasd}'
      - 'TIMEOUT=120'
      - 'FORWARD_STDERR=true'

    networks:
      - misc_challenges


  misc3:
    build: ./challs/misc/calc1
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10020:1337'
    volumes:
      - './challs/misc/calc1/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{asdasd}'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

    networks:
      - misc_challenges



  misc4:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true

    ports:
      - '10030:1337'
    volumes:
      - './challs/misc/calc2/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{asdasd}'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

    networks:
      - misc_challenges


  binary3:
    image: cybersecnatlab/challenge-jail:ubuntu-focal@sha256:5a527a362177415e717aa3d8bad646513ebd648da1f72fe012639176e228884f
    restart: unless-stopped
    init: true
    privileged: true

    ports:
      - '20010:1337'
    volumes:
      - './challs/binary/pswgenerator/pswgenerator:/home/user/chall:ro'

    environment:
      - 'FLAG=asdasdasdasdasd'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

    networks:
      - binary_challenges